sequenceDiagram
    User->>+Browser:Type text into input field
    User->>+Browser:Press submit button
    Note over Brwser, Server: Onsubmit function create new note, push it and clean value of input field.<br/> After that call redrawNotes function wich recreate list of notes 
    Browser->>+Server: Send POST request to https://studies.cs.helsinki.fi/exampleapp/new_note_spa 
    Server-->>-Browser: responds with HTTP status code 201 Created

