sequenceDiagram
    Browser->>+Server: Send GET request to https://studies.cs.helsinki.fi/exampleapp/spa
    Server-->>-Browser: Responds with spa.html
    Browser->>+Server: Send GET request to server for main.css
    Browser->>+Server: Send GET request to server for spa.js
    Browser->>+Server: Send GET request to server for data.json
     Server-->>-Browser: Responds with main.css
     Server-->>-Browser: Responds with spa.js
     Server-->>-Browser: Responds with data.json
